import provider_config_case_support as _provider_config_case_support  # noqa: F401  # Bootstraps src.
import provider_config_conversion_cases as conversion_cases
import provider_config_credential_cases as credential_cases
import provider_config_proxy_cases as proxy_cases

test_openai_local_api_base_uses_bare_catalog_model_on_wire = (
    conversion_cases.test_openai_local_api_base_uses_bare_catalog_model_on_wire
)
test_openai_catalog_model_id_strips_only_openai_route_prefix = (
    conversion_cases.test_openai_catalog_model_id_strips_only_openai_route_prefix
)
test_openai_without_local_api_base_keeps_qualified_model = (
    conversion_cases.test_openai_without_local_api_base_keeps_qualified_model
)
test_non_openai_local_api_base_is_unchanged_by_openai_bare_wire_rule = (
    conversion_cases.test_non_openai_local_api_base_is_unchanged_by_openai_bare_wire_rule
)
test_fireworks_v2_api_base_rewrites_fireworks_models = (
    conversion_cases.test_fireworks_v2_api_base_rewrites_fireworks_models
)
test_fireworks_api_base_alias_is_trimmed_and_not_registered_as_fireworks_v2 = (
    conversion_cases.test_fireworks_api_base_alias_is_trimmed_and_not_registered_as_fireworks_v2
)
test_provider_config_does_not_read_legacy_fireworks_keys = (
    conversion_cases.test_provider_config_does_not_read_legacy_fireworks_keys
)
test_opencode_go_messages_uses_anthropic_provider_with_unsuffixed_base = (
    conversion_cases.test_opencode_go_messages_uses_anthropic_provider_with_unsuffixed_base
)
test_opencode_go_messages_strips_v1_base_for_litellm_anthropic = (
    conversion_cases.test_opencode_go_messages_strips_v1_base_for_litellm_anthropic
)
test_discover_api_keys_maps_fireworks_v2_key_to_fireworks_provider = (
    conversion_cases.test_discover_api_keys_maps_fireworks_v2_key_to_fireworks_provider
)
test_discover_api_keys_maps_ollama_shell_keys_to_ollama_cloud_provider = (
    conversion_cases.test_discover_api_keys_maps_ollama_shell_keys_to_ollama_cloud_provider
)
test_discover_api_keys_deduplicates_same_value_after_provider_alias_mapping = (
    conversion_cases.test_discover_api_keys_deduplicates_same_value_after_provider_alias_mapping
)
test_discover_api_keys_maps_openrouter_free_keys_to_non_zdr_provider = (
    conversion_cases.test_discover_api_keys_maps_openrouter_free_keys_to_non_zdr_provider
)
test_discover_api_keys_ignores_numbered_non_api_key_aliases = (
    conversion_cases.test_discover_api_keys_ignores_numbered_non_api_key_aliases
)
test_discover_api_keys_skips_empty_values_and_proxy_key = (
    conversion_cases.test_discover_api_keys_skips_empty_values_and_proxy_key
)
test_proxy_main_env_normalizer_materializes_numbered_ollama_cloud_alias = (
    proxy_cases.test_proxy_main_env_normalizer_materializes_numbered_ollama_cloud_alias
)
test_proxy_main_env_normalizer_clears_parent_disabled_when_durable_env_omits_it = (
    proxy_cases.test_proxy_main_env_normalizer_clears_parent_disabled_when_durable_env_omits_it
)
test_proxy_main_env_normalizer_preserves_durable_disabled_when_explicitly_set = (
    proxy_cases.test_proxy_main_env_normalizer_preserves_durable_disabled_when_explicitly_set
)
test_proxy_main_durable_ollama_alias_overrides_inherited_cloud_alias = (
    proxy_cases.test_proxy_main_durable_ollama_alias_overrides_inherited_cloud_alias
)
test_proxy_main_credential_summary_counts_only_and_omits_identifiers = (
    credential_cases.test_proxy_main_credential_summary_counts_only_and_omits_identifiers
)
test_proxy_main_startup_credential_summary_is_count_only = (
    credential_cases.test_proxy_main_startup_credential_summary_is_count_only
)
test_proxy_main_startup_display_does_not_include_raw_proxy_key = (
    credential_cases.test_proxy_main_startup_display_does_not_include_raw_proxy_key
)
